name: Web Build + Deployment to GitHub Pages 

on:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches: 
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.11.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.8

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Flet Version
      run: |
        pip show flet || echo "Flet is not installed"
        flet --version || echo "Flet CLI is not installed"

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Flet Build Web
      run: |
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"
        flet build web --base-url ${GITHUB_REPOSITORY#*/} --route-url-strategy hash
        if [ ! -f "app/app.zip" ]; then
          echo "Flet build failed: app/app.zip was not created."
          echo "Listing contents of current directory for debugging:"
          ls -l
          echo "Listing contents of app directory for debugging:"
          ls -l app/
          echo "Checking for errors in the flet build process:"
          cat flet_build.log || echo "No log file found"
          exit 1

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build-artifact
        path: build/web

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
